### PR TITLE
PHP 8 and PHP 8.1 support

### PR DESCRIPTION
**Pull request by anibalsanchez**
Please, check the PR with support for PHP 8 and PHP 8.1. It works Ok for v8.0, but I have to fix a compatibility issue on PHP 8.1. I also added a couple of minor optimizations.

Great project!

### CODE REVIEW

**Comment by anibalsanchez** [comment]
The issue on PHP 8.1 could be an issue on PHP itself... let's see: https://github.com/php/php-src/issues/7770

**Comment by anibalsanchez** [comment]
It is not a bug on PHP and it must be fixed. In our case, it looks like `ENT_SUBSTITUTE` is the best approach.

The new behavior is explained here: https://github.com/php/php-src/issues/7770#issuecomment-992861017

**Comment by anibalsanchez** [comment]
Correction, fixed to `htmlspecialchars($string, ENT_QUOTES | ENT_SUBSTITUTE)` for all PHP versions. Check: https://php.watch/versions/8.1/html-entity-default-value-changes

**Comment by validaide-cristian-navalici** [comment]
Integrated into https://github.com/validaide/html-builder/pull/6, due to some outdated code.

**Pull request closed without merging**
